# Generated by Django 3.1.3 on 2020-11-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0004_profile_id_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Id_profile',
        ),
    ]
