# Generated by Django 2.2.7 on 2020-12-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0005_remove_profile_id_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_Id',
            field=models.IntegerField(default=0),
        ),
    ]
